routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\TranslationController;
use App\Http\Controllers\StateController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\ReportController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Ruta home para admin
Route::get('/home', [HomeController::class, 'index'])->name('home');

//Ruta home para usuario
Route::get('/user', [HomeController::class, 'getUser'])->name('user-home');

//Grupo de rutas para proyecto
Route::middleware(['auth', 'verifyAdmin'])->group(function () {
    Route::resource('categories', CategoryController::class);
    Route::resource('movies', MovieController::class);
    Route::resource('transactions', TransactionController::class); 
    //Rutas para reportes
    Route::get('/reports/users-report', [ReportController::class, 'getUsersData'])->name('report.users-report');
    Route::get('/reports/users-report/download-pdf', [ReportController::class, 'downloadUserReportPdf'])->name('report.users.download-pdf');   
    Route::get('/reports/users-report/download-excel', [ReportController::class, 'downloadUserReportExcel'])->name('report.users.download-excel');   
});

//Ruta para los detalles de la película
Route::get('/user-show/{id}', [MovieController::class, 'userShow'])->name('movies.user-show');
//Ruta para comprar pelicula
Route::post('/transactions/buy/{id}', [TransactionController::class, 'buy'])->name('transactions.buy');
//Ruta para rentar pelicula
Route::post('/transactions/rent/{id}', [TransactionController::class, 'rent'])->name('transactions.rent');
//Ruta para listar peliculas rentadas 
Route::get('/moviest/rented', [MovieController::class, 'rentedMovies'])->name('movies.rented');
//Ruta para deolver peliculas
Route::post('/movies/return/{id}', [MovieController::class, 'returnMovie'])->name('movies.return-movie');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
		'name', 'description'
	];

	public function my_update($request){       
        self::update($request->all());
    }

    public function movies(){
		return $this->hasMany(Movie::class);
	}
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //retorno a vista junto a las categorías
        return view('category.index', [
            'categories' => Category::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //retorno a vista con formulario para registrar
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validando la request
        $request->validate([            
            'name' => 'required',
            'description' => 'required',                       
        ],
        [//colocando mensajes de error en cada caso          
            'name.required' => 'El nombre es requerido',
            'description.required' => 'La descripción es requerida.'                
        ]);
        //creando la categía y redireccionando con 'created' para indicar que se creó bien
        Category::create($request->all());
        return redirect()->route('categories.index')->with('created', 'ok');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //retornando a vista para editar formulario, enviando la categoría a editar
        return view('category.edit', [
            'category' => $category
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //validando la request
        $request->validate([            
            'name' => 'required',
            'description' => 'required',                       
        ],
        [//colocando mensajes de error en cada caso          
            'name.required' => 'El nombre es requerido',
            'description.required' => 'La descripción es requerida.'                
        ]);
        //se utiliza funcion update creada en modelo
        $category->my_update($request);
        return redirect()->route('categories.index')->with('edited', 'ok');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //se elimina la categoría y se retorna al index junto con "deleted" para indicar que se elimino
        $category->delete();
        return redirect()->route('categories.index')->with('deleted', 'ok');
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <form action="{{ route('categories.store') }}" method="POST">
            @csrf
            <div class="card">
                <div class="card-header">
                    <h2>Crear categoría</h2>
                </div>
                <div class="card-body">          
                    <div class="form-row">
                        <div class="form-group col-md-12">

                            <label for="name">Nombre</label>
                            <span class="fa fa-building   form-control-feedback"></span>
                            <input type="text" class="form-control" name="name" id="name" placeholder="" value="{{ old('name') }}">                                                       
                            @error('name')
                                <span class=”invalid-feedback” role=”alert”>
                                    <i class="fa fa-exclamation" aria-hidden="true" class="text-danger"></i>
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                            @enderror

                            <label for="description">Descripción</label>
                            <span class="fa fa-building   form-control-feedback"></span>
                            <textarea class="form-control" name="description" cols="4" id="description"></textarea>                                                     
                            @error('description')
                                <span class=”invalid-feedback” role=”alert”>
                                    <i class="fa fa-exclamation" aria-hidden="true" class="text-danger"></i>
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>                    
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <form action="{{ route('categories.update', $category) }}" method="POST">
            @csrf
            {{ method_field('PUT') }}
            <div class="card">
                <div class="card-header">
                    <h2>Editando categoría {{$category->name}}</h2>
                </div>
                <div class="card-body">          
                    <div class="form-row">
                        <div class="form-group col-md-12">

                            <label for="name">Nombre</label>
                            <span class="fa fa-building   form-control-feedback"></span>
                            <input type="text" class="form-control" name="name" id="name" placeholder="" value="{{$category->name}}">                                                       
                            @error('name')
                                <span class=”invalid-feedback” role=”alert”>
                                    <i class="fa fa-exclamation" aria-hidden="true" class="text-danger"></i>
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                            @enderror

                            <label for="description">Descripción</label>
                            <span class="fa fa-building   form-control-feedback"></span>
                            <textarea class="form-control" name="description" cols="4" id="description">{{$category->description}}</textarea>                                                     
                            @error('description')
                                <span class=”invalid-feedback” role=”alert”>
                                    <i class="fa fa-exclamation" aria-hidden="true" class="text-danger"></i>
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>                    
                    <button type="submit" class="btn btn-primary">Actualizar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')
@section('css')
    <!-- CSS DATA TABLE -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.6/css/responsive.bootstrap4.min.css">
@endsection

@section('content')

<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="ml-1">
                <h2>Categorías</h2>
                <p></p>
            </div>
            <div class="pull-left">
                <a href="{{ route('categories.create') }}" class="btn btn-outline-success">
                    {{ __('Agregar categoría') }}
                </a>
            </div>               
            <br>
            <div class="card">
                <div class="card-body">
                    <table class="table table-stripped table-responsive  tex-center" style="width: 100%"
                    id="clients">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Descripción</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>

                    @foreach ($categories as $item)
                        <tr id="sid{{ $item->id }}">
                            <td>{{ $item->id }}</td>
                            <td>{{ $item->name }}</td>                            
                            <td>            
                            <div class="row">
                                <div class="col">
                                    <a href="{{ route('categories.edit', $item) }}" class="btn" style="background-color: #FDC02E" title="Editar categoría"><i class="fa fa-pencil" aria-hidden="true">Editar</i>
                                    </a>     
                                </div>

                                <div class="col">
                                    <form action="{{ route('categories.destroy', $item) }}" method="post">
                                            {{csrf_field()}}
                                            {{ method_field('DELETE') }}
                                            <button class="btn btn-danger" type="submit">Eliminar</button>
                                    </form>
                                </div>
                            </div>
                            </td>
                        </tr>
                    @endforeach

                </tbody>
            </table>
        </div>
    </div>
</div>
</div>


</div>

@endsection

@section('js')
    {{-- JS DATATABLE --}}
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js" defer></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js" defer></script>
    <script src="https://cdn.datatables.net/responsive/2.2.6/js/dataTables.responsive.min.js" defer></script>
    <script src="https://cdn.datatables.net/responsive/2.2.6/js/responsive.bootstrap4.min.js" defer></script>
    <script>
        $(document).ready(function() {
            $('#clients').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
                }
            });
        });

    

    </script>
    @if (Session::has('created'))
        <script>
            toastr.success("Categoría creada.");
        </script>
    @endif
    @if (Session::has('deleted'))
        <script>
            toastr.error("Categoría eliminada.");
        </script>
    @endif
    @if (Session::has('edited'))
        <script>
            toastr.success("Categoría editada.");
        </script>
    @endif
@endsection