routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\TranslationController;
use App\Http\Controllers\StateController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\ReportController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Ruta home para admin
Route::get('/home', [HomeController::class, 'index'])->name('home');

//Ruta home para usuario
Route::get('/user', [HomeController::class, 'getUser'])->name('user-home');

//Grupo de rutas para proyecto
Route::middleware(['auth', 'verifyAdmin'])->group(function () {
    Route::resource('categories', CategoryController::class);
    Route::resource('movies', MovieController::class);
    Route::resource('transactions', TransactionController::class); 
    //Rutas para reportes
    Route::get('/reports/users-report', [ReportController::class, 'getUsersData'])->name('report.users-report');
    Route::get('/reports/users-report/download-pdf', [ReportController::class, 'downloadUserReportPdf'])->name('report.users.download-pdf');   
    Route::get('/reports/users-report/download-excel', [ReportController::class, 'downloadUserReportExcel'])->name('report.users.download-excel');   
});

//Ruta para los detalles de la película
Route::get('/user-show/{id}', [MovieController::class, 'userShow'])->name('movies.user-show');
//Ruta para comprar pelicula
Route::post('/transactions/buy/{id}', [TransactionController::class, 'buy'])->name('transactions.buy');
//Ruta para rentar pelicula
Route::post('/transactions/rent/{id}', [TransactionController::class, 'rent'])->name('transactions.rent');
//Ruta para listar peliculas rentadas 
Route::get('/moviest/rented', [MovieController::class, 'rentedMovies'])->name('movies.rented');
//Ruta para deolver peliculas
Route::post('/movies/return/{id}', [MovieController::class, 'returnMovie'])->name('movies.return-movie');

app/Models/Movie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
    use HasFactory;

    protected $fillable = [
		'name', 
		'picture', 
		'description',
		'year',
		'price',
		'rent_price',
		'category_id',
		'state_id'
	];

	public function state(){
		return $this->hasOne(State::class);
	}
	public function category(){
		return $this->hasOne(Category::class);
	}
	public function transactions(){
		return $this->hasMany(Transaction::class);
	}
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use Storage;
use App\Models\Movie;
use App\Models\Category;
use App\Models\Transaction;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class MovieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //retorno a vista junto a las peliculas
        return view('movie.index', [
            'movies' => Movie::all(),
            'categories' => Category::all()
        ]);
    }


    public function rentedMovies()
    {
        $movies = DB::select("select m.id, t.id as 'tranId',m.name, m.year, t.debt from movies m inner join transactions t 
            on t.movie_id = m.id
            where t.type = 'A' and t.open = 1 and t.user_id = ?", [Auth::user()->id]);

        return view('movie.rented-index', [
            'movies' => $movies
        ]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //retorno a vista con formulario para registrar
        return view('movie.create', [
            'categories' => Category::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validando la request
        $request->validate([            
            'name' => 'required',
            'description' => 'required',   
            'picture' => 'required',
            'year' => 'required', 
            'price' => 'required',
            'category_id' => 'required',            
        ],
        [//colocando mensajes de error en cada caso          
            'name.required' => 'El nombre es requerido',
            'description.required' => 'La descripción es requerida.',
            'picture.required' => 'La portada es requerida.',
            'year.required' => 'El año es requerido.',
            'price.required' => 'El precio es requerido.',
            'category_id.required' => 'La categoría es requerida.'
        ]);

        $file = $request->file('picture');
        $extension = $file->getClientOriginalExtension();
        $nombre=$file->getClientOriginalName();
        Storage::disk('public')->put($nombre,  \File::get($file));
        $pathToFile = $nombre;

        $movie = Movie::create([
            'name' => $request['name'],
            'year' => $request['year'],
            'description' => $request['description'],
            'picture' => $pathToFile,
            'category_id' => $request['category_id'],
            'price' => $request['price'],
            'rent_price' => ($request['price'] * 0.25),
            'state_id' => 1            
        ]);
        return redirect()->route('movies.index')->with('created', 'ok');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function show(Movie $movie)
    {
        return view('movie.show', [
            'movie' => $movie,
            'categories' => Category::all()
        ]);
    }

    public function userShow($id)
    {
        $movie = Movie::find($id);
        return view('movie.user-show', [
            'movie' => $movie,
            'categories' => Category::all()
        ]);
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function edit(Movie $movie)
    {
        //retornando a vista para editar formulario, enviando la pelicula a editar
        return view('movie.edit', [
            'movie' => $movie,
            'categories' => Category::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validando la request
        $request->validate([            
            'name' => 'required',
            'description' => 'required',   
            'year' => 'required', 
            'price' => 'required',
            'category_id' => 'required',            
        ],
        [//colocando mensajes de error en cada caso          
            'name.required' => 'El nombre es requerido',
            'description.required' => 'La descripción es requerida.',
            'year.required' => 'El año es requerido.',
            'price.required' => 'El precio es requerido.',
            'category_id.required' => 'La categoría es requerida.'
        ]);
        //verifica si se cambio la imagen de portada
        if($request->hasFile('picture') ){
            $file = $request->file('picture');
            $extension = $file->getClientOriginalExtension();
            $nombre=$file->getClientOriginalName();
            Storage::disk('public')->put($nombre,  \File::get($file));
            $pathToFile = $nombre;
            //se sube la nueva imagen y se cambia en la bdd
            $movie = Movie::find($id);
            $movie->name = $request['name'];
            $movie->description = $request['description'];
            $movie->year = $request['year'];
            $movie->price = $request['price'];
            $movie->rent_price = ($request['price'] * 0.25);
            $movie->category_id = $request['category_id'];
            $movie->picture = $pathToFile;
            $movie->save();
        }else{
            //se realiza un update normal sin cambiar la imagen de portada
            $movie = Movie::find($id);
            $movie->name = $request['name'];
            $movie->description = $request['description'];
            $movie->year = $request['year'];
            $movie->price = $request['price'];
            $movie->rent_price = ($request['price'] * 0.25);
            $movie->category_id = $request['category_id'];
            $movie->picture = $request['pathToFile'];
            $movie->save();
        }        
        return redirect()->route('movies.index')->with('edited', 'ok');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function destroy(Movie $movie)
    {
        //se elimina la pelicula y se retorna al index junto con "deleted" para indicar que se elimino
        $movie->delete();
        return redirect()->route('movies.index')->with('deleted', 'ok');
    }

    public function returnMovie(Request $request, $id)
    {
        //Crear transaccion de tipo Retorno
        $returnTransaction = Transaction::create([
            'type' => 'R',
            'user_id' => $request['user_id'],
            'movie_id' => $id,
            'open' => false,
            'debt' => $request['debt']
        ]);
        //se cambia la transaccion de alquilada a cerrado (open = false)
        $rentedTransaction = Transaction::find($request['transactionId']);
        $rentedTransaction->open = false;
        $rentedTransaction->save();
        return redirect()->route('movies.rented')->with('returned', 'ok');
    }
}

resources/views/movie/create.blade.php
@extends('layouts.app')
@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/css/datepicker.min.css" rel="stylesheet">
@endsection
@section('content')
    <div class="container">
        <form action="{{ route('movies.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="card">
                <div class="card-header">
                    <h2>Crear película</h2>
                </div>
                <div class="card-body">         
                    <div class="form-row justify-content-center align-items-center">
                        <div class="">
                            <div class="form-outline mb-4">
                                <label for="name">Nombre</label>
                                <span class="fa fa-building   form-control-feedback"></span>
                                <input type="text" class="form-control" name="name" id="name" placeholder="" value="{{ old('name') }}">                                                       
                                @error('name')
                                    <span class=”invalid-feedback” role=”alert”>
                                        <i class="fa fa-exclamation" aria-hidden="true" class="text-danger"></i>
                                        <strong class="text-danger">{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-outline mb-4">
                                <label for="description">Sinopsis</label>
                                <span class="fa fa-building   form-control-feedback"></span>
                                <textarea class="form-control" name="description" cols="4" id="description"></textarea>                                                     
                                @error('description')
                                    <span class=”invalid-feedback” role=”alert”>
                                        <i class="fa fa-exclamation" aria-hidden="true" class="text-danger"></i>
                                        <strong class="text-danger">{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-outline mb-4">
                                <label for="picture">Portada</label>
                                <span class="fa fa-building   form-control-feedback"></span>
                                <div class="file-field input-field">
                                    <div class="form-group">                                        
                                        <input type="file" name="picture" class="form-control-file" id="picture">
                                    </div>

                                    @error('picture')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-outline mb-4">
                                <label for="year">Año de estreno</label>
                                <span class="fa fa-building   form-control-feedback"></span>
                                <input type="number" class="form-control" name="year" id="datepicker" />                                                     
                                @error('year')
                                    <span class=”invalid-feedback” role=”alert”>
                                        <i class="fa fa-exclamation" aria-hidden="true" class="text-danger"></i>
                                        <strong class="text-danger">{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-outline mb-4">
                                <label for="price">Precio</label>
                                <span class="fa fa-building   form-control-feedback"></span>
                                <div class="input-group-addon">USD</div>
                                <input type="number" name="price" min="0.00" step="0.05" value="1.00" class="form-control" placeholder="$">
                                 
                                @error('price')
                                    <span class=”invalid-feedback” role=”alert”>
                                        <i class="fa fa-exclamation" aria-hidden="true" class="text-danger"></i>
                                        <strong class="text-danger">{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>  

                            <div class="form-outline mb-4">
                                <div class="form-group">
                                    <label for="category">Categoría</label>
                                    <select class="form-control" id="category_id" name="category_id">
                                        @foreach ($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                   </select>
                                </div>
                                 
                                @error('category_id')
                                    <span class=”invalid-feedback” role=”alert”>
                                        <i class="fa fa-exclamation" aria-hidden="true" class="text-danger"></i>
                                        <strong class="text-danger">{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>  

                            
                        </div>
                    </div>    
                    <div class="form-row justify-content-center align-items-center">
                        <button type="submit" class="btn btn-primary">Registrar</button>
                    </div>                 
                </div>
            </div>
        </form>
    </div>
@endsection
@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/js/bootstrap-datepicker.min.js"></script>

<script type="text/javascript">
    $("#datepicker").datepicker({
        format: "yyyy",
        viewMode: "years", 
        minViewMode: "years",
        autoclose:true
    });
</script>
@endsection

resources/views/movie/edit.blade.php
@extends('layouts.app')
@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/css/datepicker.min.css" rel="stylesheet">
@endsection
@section('content')
    <div class="container">
        <form action="{{ route('movies.update', $movie->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            {{ method_field('PUT') }}
            <div class="card">
                <div class="card-header">
                    <h2>Editando película : {{$movie->name}}</h2>
                </div>
                <div class="card-body">         
                    <div class="form-row justify-content-center align-items-center">
                        <div class="">
                            <div class="form-outline mb-4">
                                <label for="name">Nombre</label>
                                <span class="fa fa-building   form-control-feedback"></span>
                                <input type="text" class="form-control" name="name" id="name" placeholder="" value="{{ $movie->name }}">                                                       
                                @error('name')
                                    <span class=”invalid-feedback” role=”alert”>
                                        <i class="fa fa-exclamation" aria-hidden="true" class="text-danger"></i>
                                        <strong class="text-danger">{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-outline mb-4">
                                <label for="description">Sinopsis</label>
                                <span class="fa fa-building   form-control-feedback"></span>
                                <textarea class="form-control" name="description" cols="4" id="description">{{$movie->description}}</textarea>                                                     
                                @error('description')
                                    <span class=”invalid-feedback” role=”alert”>
                                        <i class="fa fa-exclamation" aria-hidden="true" class="text-danger"></i>
                                        <strong class="text-danger">{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-outline mb-4">
                                <input type="hidden" name="pathToFile" value="{{$movie->picture}}">
                                <label for="picture">Portada</label>
                                <span class="fa fa-building   form-control-feedback"></span>
                                <div class="file-field input-field">
                                    <div class="form-group">                                        
                                        <input type="file" name="picture" class="form-control-file" id="picture">
                                    </div>

                                    @error('picture')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-outline mb-4">
                                <label for="year">Año de estreno</label>
                                <span class="fa fa-building   form-control-feedback"></span>
                                <input type="number" class="form-control" name="year" id="datepicker" value="{{$movie->year}}" />                                                     
                                @error('year')
                                    <span class=”invalid-feedback” role=”alert”>
                                        <i class="fa fa-exclamation" aria-hidden="true" class="text-danger"></i>
                                        <strong class="text-danger">{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-outline mb-4">
                                <label for="price">Precio</label>
                                <span class="fa fa-building   form-control-feedback"></span>
                                <div class="input-group-addon">USD</div>
                                <input type="number" name="price" min="0.00" step="0.05" value="{{$movie->price}}" class="form-control" placeholder="$">
                                 
                                @error('price')
                                    <span class=”invalid-feedback” role=”alert”>
                                        <i class="fa fa-exclamation" aria-hidden="true" class="text-danger"></i>
                                        <strong class="text-danger">{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>  

                            <div class="form-outline mb-4">
                                <div class="form-group">
                                    <label for="category">Categoría</label>
                                    <select class="form-control" id="category_id" name="category_id">
                                        @foreach ($categories as $category)
                                            <option value="{{ $category->id }}"
                                                {{ $movie->category_id == $category->id ? 'selected' : '' }}>
                                                {{ $category->name }}
                                            </option>
                                        @endforeach
                                   </select>
                                </div>
                                 
                                @error('category_id')
                                    <span class=”invalid-feedback” role=”alert”>
                                        <i class="fa fa-exclamation" aria-hidden="true" class="text-danger"></i>
                                        <strong class="text-danger">{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>  

                            
                        </div>
                    </div>    
                    <div class="form-row justify-content-center align-items-center">
                        <button type="submit" class="btn btn-primary">Actualizar</button>
                    </div>                 
                </div>
            </div>
        </form>
    </div>
@endsection
@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/js/bootstrap-datepicker.min.js"></script>

<script type="text/javascript">
    $("#datepicker").datepicker({
        format: "yyyy",
        viewMode: "years", 
        minViewMode: "years",
        autoclose:true
    });
</script>
@endsection

resources/views/movie/index.blade.php
@extends('layouts.app')
@section('css')
    <!-- CSS DATA TABLE -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.6/css/responsive.bootstrap4.min.css">
@endsection

@section('content')

<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="ml-1">
                <h2>Películas</h2>
                <p>Lista de las películas registradas</p>
            </div>
            <div class="pull-left">
                <ul>
                    <a href="{{ route('movies.create') }}" class="btn btn-outline-success">
                        {{ __('Agregar película') }}
                    </a>   
                    <button class="btn btn-primary" id="dispo">Disponible</button>
                    <button class="btn btn-primary" id="indispo">Indisponible</button>
                </ul>
            </div>               
            <br>
            <div class="card">
                <div class="card-body">
                    <table class="table table-stripped table-responsive  tex-center" style="width: 100%"
                    id="movies">                                                
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Año</th>
                            <th>Disponibilidad</th>
                            <th>Categoría</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>

                    @foreach ($movies as $item)
                        <tr>
                            <td>{{ $item->id }}</td>
                            <td>{{ $item->name }}</td>  
                            <td>{{ $item->year }}</td>                          
                            @if ($item->state_id == 2)                                 
                                <td>Comprada</td>
                            @elseif($item->state_id == 3)
                                <td>Alquilada</td>
                            @else
                                <td>Disponible</td> 
                            @endif

                            <td>
                                @foreach ($categories as $category)
                                    {{ $item->category_id == $category->id ? $category->name : '' }}

                                                
                                @endforeach
                            </td>   
                            <td>            
                                <form action="{{ route('movies.destroy', $item) }}" method="post">
                                    {{csrf_field()}}
                                    {{ method_field('DELETE') }}

                                    <a href="{{ route('movies.show', $item) }}" class="btn" style="background-color: #3498DB" title="Más información"><i class="fa fa-pencil" aria-hidden="true">Detalles</i>
                                    </a>     

                                    <a href="{{ route('movies.edit', $item) }}" class="btn" style="background-color: #FDC02E" title="Editar película"><i class="fa fa-pencil" aria-hidden="true">Editar</i>
                                    </a>    
                                     
                                    <button class="btn btn-danger" type="submit">Eliminar</button>
                                </form>

                            </td>
                        </tr>
                    @endforeach

                </tbody>
            </table>
        </div>
    </div>
</div>
</div>


</div>

@endsection

@section('js')
    {{-- JS DATATABLE --}}
    
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js" defer></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js" defer></script>
    
    <script>
        $(document).ready(function() {
            var table = $('#movies').DataTable({
                "search": {regex: true},
                "order": [[ 1, "asc" ]],
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
                }
            });

            $( "#dispo" ).click(function() {

                table
                .columns(3)
                .search($(this).text())
                .draw();

            });

            $( "#indispo" ).click(function() {

                table
                .columns(3)
                .search("Comprada|Alquilada", true, false)
                .draw();

            });

        });

    </script>
    @if (Session::has('created'))
        <script>
            toastr.success("Película creada.");
        </script>
    @endif
    @if (Session::has('deleted'))
        <script>
            toastr.error("Película eliminada.");
        </script>
    @endif
    @if (Session::has('edited'))
        <script>
            toastr.success("Película editada.");
        </script>
    @endif
@endsection